apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: file-store
  name: file-store-service
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: file-store
  type: NodePort
